// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;

namespace Microsoft.AspNetCore.Mvc.ModelBinding
{
    /// <summary>
    /// An error created during model validation.
    /// </summary>
    public class ModelError
    {
        /// <summary>
        /// Constructs the <see cref="ModelError"/>.
        /// </summary>
        /// <param name="exception">The exception generated by model validation.</param>
        public ModelError(Exception exception)
            : this(exception, errorMessage: null)
        {
            if (exception == null)
            {
                throw new ArgumentNullException(nameof(exception));
            }
        }

        /// <summary>
        /// Constructs the <see cref="ModelError"/>.
        /// </summary>
        /// <param name="exception">The exception generated by model validation.</param>
        /// <param name="errorMessage">The message generated by model validation.</param>
        public ModelError(Exception exception, string errorMessage)
            : this(errorMessage)
        {
            if (exception == null)
            {
                throw new ArgumentNullException(nameof(exception));
            }

            Exception = exception;
        }

        /// <summary>
        /// Constructs the <see cref="ModelError"/>.
        /// </summary>
        /// <param name="errorMessage">The message generated by model validation.</param>
        public ModelError(string errorMessage)
        {
            ErrorMessage = errorMessage ?? string.Empty;
        }

        /// <summary>
        /// The exception generated by model validation.
        /// </summary>
        public Exception Exception { get; }

        /// <summary>
        /// The message generated by model validation.
        /// </summary>
        public string ErrorMessage { get; }
    }
}
